# docker/docker-compose.yml
version: '3.11'
services:
  ingestion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    # Mapea puertos si fuera necesario, monta volúmenes para logs, etc.
    volumes:
      - ./logs:/app/logs

  # Ejemplo (opcional) para un servicio Kafka local:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
